### ISSUE TITLE
(On-Site Wizard) NEBs represented in the internal data model and can be associated with Projects

### ISSUE THREAD

**Issue by ghost** [NREL/NEB-Tool#101]
- [x] Each project contains one or more NEBs.   In some cases no additional NEBs may be identified.
- [x] A project can contain many NEBs, selected by the user.
- [x] NEBs will be sorted into categories, or buckets.   .
- [x] The cost of a NEB will be pre-set as a default value  . 
- [ ] NEBs have default values   which are provided by the NEB-Tool, but can be changed by users at the project level.
- [x] NEBs may have extra properties, such as “Example of indicator” 

This epic roughly corresponds to requirement 6.3.3 in the requirements doc.

**Comment by ghost** [comment]
As of v0.0.1-alpha-c933213 this epic is well on it's way to completion, but some details remain open. We can discuss how to proceed at the next standup.

We have replaced the concept of a "Project" with "Energy Opportunities" inside of "Assessments". NEBs can be assigned at both the Assessment and Energy Opportunity level in the second wizard.

Completed Items:
- **Each project contains one or more NEBs. In some cases no additional NEBs may be identified.** Yes
- **A project can contain many NEBs, selected by the user:** Currently implemented in the Data Collection wizard within each assessment. User can select NEBs at both the Assessment and the Energy Opportunity level.
- **NEBs may have extra properties, such as “Example of indicator”:** Currently implemented as the KPI/NEB matrix. This is hidden from the user right now, but the property is used to hide certain NEBs which are irrelevant to the project. This one probably needs more refinement, but I think we can call it satisfied for now.

Outstanding items:
- **NEBs will be sorted into categories, or buckets:** The current view for selecting NEBs is a simple grid (See Screenshot 1). The idea is to have these NEBs sorted and searchable by KPI. Need to refine the NEBs selection modal and add this feature. Again, I think we need a common UI language for these selection modals (Selecting KPIs, Team Members, and NEBs, could all be unified in design).
- **The cost of a NEB will be pre-set as a default value:** While the baseline cost of each KPI is configured at the project level and propagated into the NEB, neither the baseline KPI cost nor the "NEB Impact" field have default values right now.

Screenshot 1:
<img width="1076" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeC9GQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3126ff2be4ab38c764bc95df95db40ae82082990/Screenshot%202024-07-09%20at%208.15.13%20AM.png" alt="Screenshot 2024-07-09 at 8.15.13 AM.png" />

**Comment by ghost** [comment]
Default values are not implemented yet, but added new issue [ZH6](https://app.zenhub.com/workspaces/justifi---neb---ornl---nrel-61080603e73e7b0011bbdd7d/issues/zh/6)
