### ISSUE TITLE
NEB Arrangements UI

### ISSUE THREAD

**Issue by ghost** [NREL/NEB-Tool#110]
Based on feedback from the stakeholder demo, we found that the many-to-many UI for NEBs is a bit confusing.

- [ ] Limit the NEBs to be one-to-many in the initial association view in the on-site wizard.
- [ ] Explore limiting the view to one energy opportunities on the page at a time (multiple pages) instead of having multiple energy assessments on a single page.
- [ ] Explore removing the box at the top of the screen that lists all nebs, in favor of a simpler two-column (or two-div) layout.
