### ISSUE TITLE
Verbiage revisit later

### ISSUE THREAD

**Issue by koay9f** [NREL/NEB-Tool#234]
Documentation team to revisit later:

Welcome message: revisit this intro sentence to capture how identifying NEBs should bring attention to the broader impacts of energy efficiency opportunities
KPI naming convention, for example, Reduce Expense Cost
update KPI description text
revisit Industrial system inventory field names, review the field names that will change based on the Industrial System selected above
NEB card: Revisit the terminology “Performance Metric” and “Impacts”
NEBs tab: revisit this page when implementing a section for the NEBs that can’t be tied to a particular Energy Eff Opp,
NEB tab: Revisit this page when additionally implementing a section for NEBs that all in the same category and are best represented as a cumulative/aggregate calculation
Report: Savings need consistency throughout? Revisit the words around savings/cost/benefits/impact

**Comment by rmroot** [comment]
Verbiage Check Notes 2:

- [x] Intro statement on landing screen "Use this tool to identify, estimate potential and report on non-energy benefits.."
- [x] Desired Impact -> Expected Impact (direction?)
- [x] KPI descriptions -> Sarah will be developing descriptions, but for now it's generic Latin placeholder (#263)
- [x] Maintenance expense -> needs to be a higher-level category -> requires further discussion on this type of concern. (#264)
- [x] Industrial system inventory -> not all items are applicable, but it's OK for now. Will need to expand table. Note during the demo that this is in draft and move through quickly. Also need to revisit units for matching to the proper component. (#163)
- [x] Performance Metric Impact -> "Key Performance …" (don't leave off "Key" anywhere)
- [ ] Assessment Non-Energy Benefits -> Help text example that highlights what 'specific' means.
- [x] KPI Selection -> move this down into Facilities; tease apart Facility KPI from Corporate KPIs and connect the two. (#265)
- [x] Results -> Additional Operational Benefits-> requires further discussion (#239 ?)

Updated bullets with new issues

**Comment by koay9f** [comment]
Missed a "Performance Metric" (related to button)
`Fill out the impacts on company performance metrics () that can be associated with this Non-energy Benefit. Click the "Search Performance Metrics" button and a modal will appear to find and add performance metrics that are typically associated with this NEB.`
