### ISSUE TITLE
Feedback from Board Meeting

### ISSUE THREAD

**Issue by koay9f** [NREL/NEB-Tool#293]
Need to break up into individual issues and decide if/when to take up. 

**Actionable Feedback (may need approval from DOE to include):**
- [x] Since inputs are spread across many separate pages, suggest an overall progress bar or percentage tracker and indicate which sections still need to be updated.  Pull users through the process.  (#302)
- [x] Have a bar that shows the amount of savings as more NEBs are added (like tax software) (#303)
- [x] Advanced reporting: allow user to add stakeholders to review, comment, and approve the report
- [ ] Indicate which NEBs are cost reducing
- [x] ~~include Employee satisfaction - we have this in the spreadsheet, but not currently in software~~
- [ ] Should include a comment of which departments or positions would be helpful in each NEB
- [x] Make maintenance easier to find (#264)
- [x] Turn NEBs on and off would be nice (#262)
- [x] When switching from unit cost to percentage, the value doesn't change, which is confusing, for example, 10,000 units cost => 10,000 percent (#301)

**Already in place/progress:**
- [x] Need to clearly identify which fields are required vs. optional
- [x] Add "info" links (or hover pop-ups) to field labels to define terminology (#229)
- [x] Build training into the tool - explainer and instructions at the top have (#232 Knowledge Lib.)?
- [ ] * Export reports to excel, powerpoint, and pdf in progress (see notes in comment)(#129)(#300)

**Need ideas for implementation:**
- [ ] Is there a way to indicate reduce risk? Like legality, etc
- [ ] * Can the software be used in reverse?  Establish value in beginning and identity savings then fill in pre-visit (see notes in comment)

**Need clarifications:**
- [x] Percent to unit cost switch issue (#301)
- [x] I think that's where the survey will be very helpful in identifying specific roles that would be knowledgeable in energy efficiency projects and would be the target for JUSTIFI

**Comment by RLiNREL** [comment]
Some notes:
- Export reports to excel (put in the product backlog). If a report type in excel format is found, we can add it in.
- Can the software be used in reverse? This involves with NEB recommendation engine. Need to check with Nate/Bruce on their interest.

**Comment by rmroot** [comment]
"Employee Engagement/Satisfaction" is a KPM in the "Employee Engagement - Workforce Development" KPI
