### ISSUE TITLE
Wizard Overview Nav/UI

### ISSUE THREAD

**Issue by jordanperr** [NREL/NEB-Tool#95]
- [ ] Dashboard and side bar to show the progress of each assessments
- [ ] Navigate through (in and out) different wizards
- [ ] Possibly need to redesign the setup-wizard/getting-started page

Need to discuss the scoping/ priorities based on the objectives/ requirements.
----------------------------------------------------
Out of QA from #64 

**Description**:

The current "setup-wizard/getting-started" page has three main buttons, one each to create a new wizard. Each wizard does allow you to select a previously configured company, facility, and assessment. Not yet implemented is how the user might handle two wizards that reference the same company, or transfer their session working on a wizard ~~to their phone or mobile device.~~

**Supported Stories**:
- User can create new wizard.
- Multiple in progress wizards can be stored in the database.
- User can resume an in-progress wizard.

In-progress wizards overview page with:
- List of all in-progress wizards / projects.
- Ability to jump to Pre-visit, On-site, or Post-visit sections for each in-progress wizard.
- Ability to create, delete, save, and load wizards.

**Images**:

**My Projects (possible replacement for My Portfolio and Setup-Wizard/Getting-Started)**: First pass at the "setup wizard / getting started" page with in-progress wizards in the database. It is possible this is a replacement for the "My Portfolio" page. Let's discuss.

<img width="771" alt="Screenshot 2024-05-29 at 12 06 06 PM" src="https://github.com/NREL/NEB-Tool/assets/355615/1818bae9-fbc0-47c8-93ad-c94e5270d576">

**Wizard UI**: A re-designed wizard, showing all three wizards as sections (1) "Roadmap" ~ "Pre-Visit", (2) "Identify Opportunities and NEBs" ~ "Data Collection",  (3) "Evaluate and Create Reports" ~ "Data Evaluation" in the same sidebar.

<img width="794" alt="Screenshot 2024-05-29 at 11 59 55 AM" src="https://github.com/NREL/NEB-Tool/assets/355615/a5706feb-4854-4e9f-bf2c-fd6b14b28b4b">

For example, the /setup-wizard/getting-started page currently has three buttons, one for each wizard. Instead, it could be redesigned to:
- List of all in-progress wizards / projects.
- Ability to jump to Pre-visit, On-site, or Post-visit sections for each in-progress wizard.
- Ability to create, delete, save, and load wizards.

Here's a mock-up of what this page could look like:
<img width="1383" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVNWQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bc035af215f036d9300ace0475fcb12972b2c40c/Screenshot%202024-06-26%20at%204.23.10%20PM.png" alt="Screenshot 2024-06-26 at 4.23.10 PM.png" />

And here's a rough mockup of what the sidebar could look like with sections:
<img width="514" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVdWQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0a95b6c93279cad470c299796e43923e105c87f8/Screenshot%202024-06-26%20at%204.24.07%20PM.png" alt="Screenshot 2024-06-26 at 4.24.07 PM.png" />

**Comment by rmroot** [comment]
Sub issues closed for epic. Stale closing.
